version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
      
    working_directory: ~/repo
    
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
          
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
          
      - run:
          name: Analyze on SonarCloud
          command: ./gradlew build sonarqube
          
      - run: ./gradlew test --info --stacktrace

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
