version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: gradle build sonarqube"

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - run: "gradle test"
